<?php

namespace PhpIst\SolrWorkShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function prepareProductForSolr()
    {
        $products = $this->findAll();

        return $products;
    }
}
